Enchance documentation
CloudNativeSDWAN/cnwan-reader pull request #13
Opened 2020-10-13 09:43 UTC by SunSince90

This PR enhancing documentation by splitting it into multiple files and making it much more organized.

Additionally, this also updates version format to `0.x.x` and adds badges to the repository.

2020-10-30 02:54 UTC, arnatal requested changes
This looks very good Elis, thanks for the changes! I've added some minor comments, but honestly I think we can probably merge the PR as is :)

2020-10-30 02:54 UTC, arnatal commented on docs/usage.md
> +* The endpoint of the adaptor is `http://example.com:5588/my/path`
I'd use the default as example here i.e. "localhost:80"

2020-10-30 02:54 UTC, arnatal commented on docs/usage.md
> +--metadata-key prefix/key
Maybe we should provide an example related to the general CNWAN project, like "cwan.io/traffic-profile", so people coming to the Reader from one of our demos/presos can easily map what this is for.

2020-11-02 11:35 UTC, SunSince90 commented on README.md
Yeah I think that we can remove it, will be much cleaner like this

2020-11-02 11:37 UTC, SunSince90 commented on docs/docker_installation.md
> +docker pull cnwan/cnwan-reader:v0.3.0
Yes, #12 introduces a workflow that auto-builds&pushes a docker image whenever a new tag/release is created :)

2020-11-02 11:40 UTC, SunSince90 commented on docs/docker_installation.md
> +docker rename cnwan/cnwan-reader cnwan-reader
This section is unrelated from the previous and now that I read it I realize that it isnt very straightforward. I will modify it accordingly. Thank you!

2020-12-05 02:16 UTC, arnatal requested changes
Two nano fixes and we should be good to go 😄

2020-12-05 02:16 UTC, arnatal commented on docs/docker_usage.md
> +--service-account ./credentials/serv-acc.json
Let's add the --adaptor-api even if we are using the default and it's technically not needed, for clarity
```suggestion
--service-account ./credentials/serv-acc.json
--adaptor-api localhost:8080/cnwan
```

2020-12-05 02:16 UTC, arnatal commented on docs/usage.md
> +(`http://localhost/cnwan/events`), so there is no need to use `--adaptor-api`
I'd add the --adaptor-api anyways to the command below. Maybe making the comment here that it's not needed when we use the default value but we add it for clarity.

2020-12-05 02:55 UTC, arnatal commented
I just realized that we should also update the version printed via the 'version' command.

2020-12-09 09:09 UTC, SunSince90 commented
> I just realized that we should also update the version printed via the 'version' command.

Good catch! 

Also, please join #12 before this one :)

2020-12-18 04:28 UTC, merged