Support etcd
CloudNativeSDWAN/cnwan-reader pull request #26
Opened 2021-02-02 11:51 UTC by SunSince90

This pull requests bring support for the popular distributed key-value store *etcd* to the cnwan-reader.

To use etcd as a service registry, the command `etcd watch etcd [flags]` must be used and, as always, the cnwan-reader will react to all events happening on the cluster.

Please take a look at #18 to track the progress of this pr.

2021-02-02 12:05 UTC, SunSince90 commented
Note: the tests just fail because op#25 is not merged, yet

2021-06-25 13:20 UTC, ljakab requested changes
Elis, this looks very good, just a few small typo corrections/copyright year changes needed

2021-06-25 13:20 UTC, ljakab commented on pkg/cmd/watch/etcd/fake_kv.go
> +// Copyright © 2020 Cisco
s/2020/2021/

2021-06-25 13:20 UTC, ljakab commented on pkg/cmd/watch/etcd/watcher_test.go
> +// Copyright © 2020 Cisco
s/2020/2021/

2021-06-25 13:20 UTC, ljakab commented on pkg/cmd/watch/etcd/fake_queue.go
> +// Copyright © 2020 Cisco
s/2020/2021/

2021-06-25 13:20 UTC, ljakab commented on docs/docker_usage.md
> +* There is only on etcd node, on address `10.11.12.13` on default port (`2379`).
s/on/one/

2021-06-25 13:20 UTC, ljakab commented on docs/usage.md
> +* There is only on etcd node, on address `10.11.12.13` on default port (`2379`).
s/on/one/

2021-07-05 06:45 UTC, SunSince90 commented on go.mod
> +	google.golang.org/grpc => google.golang.org/grpc v1.27.1
Unfortunately, as long as etcd team does not provide a good/stable module support, this will stay like this

2021-07-19 09:16 UTC, merged